version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "uos-cc-cw-back-v1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-70yp7g1tmawu"
s3_prefix = "uos-cc-cw-back-v1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"uos-cc-cw\""

